//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaloonSharm.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderService = new HashSet<OrderService>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public bool Accepted { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<OrderService> OrderService { get; set; }
    }
}
